name: CI

on:
  push:
    branches: [main]
    pull_request: 
    branches: [main]

job: 
 test: 
  runs-on: ubuntu-latest

steps: 
 - name: Grab the code
   uses: actions/setup-checkout

name: 
Set up Node
        uses: actions/setup-node@v4
     with:
          node-version: "20"

name: Install dependencies
        run: npm ci

name: Run tests
        run: npm test
  
